---
volumes:
  Macintosh HD: []
  Ouroboros:
    - Anime
  Core:
    - Shows
    - Books
    - Movies
    - Mac Apps
    - Other Stuff
  Slayer:
    - Videos/Shows
    - Videos/Movies
    - Videos/Cartoons

